- name: change route53
  route53:
    state: present
    zone: bonduu01.com
    record: www.bonduu01.com
    failover: SECONDARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "67d5f697-c99c-45c1-b06a-cd98a7ecbc0c"
