- name: change route53
  route53:
    state: present
    zone: bonduu01.com
    record: www.bonduu01.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "505d48f8-3b07-4bad-ae3d-6227688985ca"
